controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    ackermann_steering_controller:
      type: 'ackermann_steering_controller/AckermannSteeringController'

ackermann_steering_controller:
  ros__parameters:
    wheelbase: 1.41
    front_wheel_track: 1.36
    rear_wheel_track: 1.36
    front_wheels_radius: 0.343
    rear_wheels_radius: 0.343
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['ED_DCH_joint', 'ED_IZQ_joint', 'ET_DCH_joint','ET_IZQ_joint']                  # RUEDAS MOTRICES 'ET_DCH_joint','ET_IZQ_joint',
    front_wheels_names: ['MGD_DCH_joint', 'MGD_IZQ_joint']                                             # DIRECCIÓN
    use_stamped_vel: true
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: CH
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: false
