 # Set just topic name, applies to both
# - topic_name: "cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "ignition.msgs.Twist" gz.msgs.Twist

# - topic_name: "model/panter/ET_DCH_joint/sensor/force_torque_sensor/force_torque"
#   ros_type_name: "geometry_msgs/msg/Wrench"
#   gz_type_name: "ignition.msgs.Wrench"

# - topic_name: "model/panter/ED_DCH_joint/sensor/force_torque_sensor/force_torque"
#   ros_type_name: "geometry_msgs/msg/Wrench"
#   gz_type_name: "ignition.msgs.Wrench"

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/ET_DCH_wrench"
  gz_topic_name: "/model/panter/ET_DCH_joint/sensor/force_torque_sensor/force_torque"
  ros_type_name: "geometry_msgs/msg/Wrench"
  gz_type_name: "ignition.msgs.Wrench"
  direction: GZ_TO_ROS

#   - ros_topic_name: "/diff_drive/cmd_vel"
#   gz_topic_name: "/model/diff_drive/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ