
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    steering_controller:
      type: position_controllers/JointGroupPositionController

effort_controller:
  ros__parameters:
    joints:
      - ED_IZQ_joint
      - ED_DCH_joint
      - ET_IZQ_joint
      - ET_DCH_joint

steering_controller:
  ros__parameters:
    joints:
      - MGD_DCH_joint
      - MGD_IZQ_joint

