
# controller_manager:
#   ros__parameters:
#     update_rate: 50

#     joint_effort_controller:
#       type: effort_controllers/JointGroupEffortController
#       joints:
#         - ED_DCH_joint
#         - ED_IZQ_joint
#         - ET_DCH_joint
#         - ET_IZQ_joint

# /**/position_trajectory_controller:
#   ros__parameters:
#     type: joint_trajectory_controller/JointTrajectoryController
#     joints:
#       - ED_DCH_joint
#       - ED_IZQ_joint
#       - ET_DCH_joint
#       - ET_IZQ_joint

#     command_interfaces:
#       - position

controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - ED_DCH_joint
      - ED_IZQ_joint
      - ET_DCH_joint
      - ET_IZQ_joint